include catppuccin-mocha.conf

env read_from_shell=PATH EDITOR VISUAL
editor nvim

font_family JetBrainsMono Nerd Font
font_size 16.0

modify_font cell_height 125%

background_opacity 0.97

window_padding_width 0
hide_window_decorations no
macos_titlebar_color #1e1e2e

cursor_shape block
cursor_blink_interval 0.5

enable_audio_bell no
confirm_os_window_close 0
macos_option_as_alt no
clipboard_control write-clipboard write-primary read-clipboard read-primary

tab_bar_edge bottom
tab_bar_min_tabs 2
tab_title_template [{index}] {title}
active_tab_title_template [{index}] {title}

# Prevent Hyper-D from degrading into Ctrl-D/EOT in terminal apps such as tmux.
map ctrl+shift+alt+cmd+d discard_event

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5

map shift+enter send_text all \e[13;2u
map alt+enter send_text all \e[13;3u
map ctrl+enter send_text all \e[13;5u
map ctrl+shift+enter send_text all \e[13;6u
