[tools]
atuin = "18.16.1"
bat = "0.26.1"
codex = "0.144.1"
delta = "0.19.2"
eza = "0.23.4"
fd = "10.4.2"
fzf = "0.73.1"
go = "1.26.4"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "v2.12.2"
"go:golang.org/x/tools/cmd/goimports" = "v0.47.0"
"go:golang.org/x/tools/gopls" = "v0.22.0"
"go:gotest.tools/gotestsum" = "v1.13.0"
"go:mvdan.cc/gofumpt" = "v0.10.0"
hadolint = "2.14.0"
helm = "4.2.2"
helm-ls = "0.5.4"
jq = "1.8.2"
k9s = "0.51.0"
kubectl = "1.36.2"
lazygit = "0.62.2"
lua-language-server = "3.18.2"
neovim = "0.12.3"
node = "24.18.0"
"npm:@microsoft/compose-language-service" = "0.5.0"
"npm:bash-language-server" = "5.6.0"
"npm:basedpyright" = "1.39.9"
"npm:dockerfile-language-server-nodejs" = "0.15.0"
"npm:prettier" = "3.9.4"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.23.0"
"pipx:robotcode" = { version = "2.6.2", extras = "languageserver" }
"pipx:robotframework-robocop" = "8.3.2"
"pipx:ruff" = "0.15.20"
"pipx:yamllint" = "1.38.0"
ripgrep = "15.1.0"
shellcheck = "0.11.0"
shfmt = "3.13.1"
starship = "1.26.0"
stylua = "2.5.2"
tree-sitter = "0.26.9"
tmux = "3.7b"
uv = "0.11.26"
yamlfmt = "0.21.0"
yq = "4.53.3"
zoxide = "0.9.9"
